### ISSUE TITLE
[BUG] bot responded to a virustotal link and then recursively 

### ISSUE THREAD

**Issue by GitWhatYouGive** [TeamPiped/lemmy-piped-link-bot#12] opened 2023-09-14 20:17 UTC
See this post: https://feddit.de/comment/2928645

It responds to itself, adding an additional link to the github each time. As if it's begging for someone to do something to put it out of its misery.

**Comment by freamon** [comment] 2023-09-14 23:22
It's also recursively linking youtube vids:    

e.g. https://sh.itjust.works/post/5101523 or https://sh.itjust.works/post/5084992

**Comment by CDeLeon94** [comment] 2023-09-15 00:19
The recursive issue should be fixed.

The erroneous triggering needs attention.

Another example: 

https://lemmy.ca/comment/3087764

**Comment by morcantium** [comment] 2023-09-15 18:50
Are you sure it's fixed now? Same thing happened here: [https://lemmy.dbzer0.com/comment/3057921](https://lemmy.dbzer0.com/comment/3057921). The bot is currently banned from the lemmy.dbzer0.com instance until the issue is confirmed resolved.

IMO it would make sense to limit the max number of comments your bot can make in a particular post to a sane number (say 5?) so that you can mitigate the risk of it running too wild.

**Comment by CDeLeon94** [comment] 2023-09-15 18:57
That post was made before the fix was implemented. 
Bot's code was updated about 50 minutes after the post you linked. @ 8:54 PM, Sep 14 GMT

**Comment by FireMasterK** [comment] 2023-09-15 20:44
Hey, this should have been fixed with 34eb8cb00bcda13eb0ce8f00d5f9628c88ab615e already.

**Closed** 2023-09-15 20:44 UTC
